### PR TITLE
Remove DL's from portal message in templates.

### PR DESCRIPTION
**Pull request by khink**
For Plone 5, don't merge unless a branch for that exists.
https://github.com/plone/Products.CMFPlone/issues/153

### CODE REVIEW

**Comment by jensens** [comment]
Do we need this one?

**Comment by jensens** [comment]
@khink do we still need this one?

**Comment by khink** [comment]
I'd say yes

**Comment by jensens** [comment]
So can you please rebase with master, so we can merge it?

**Pull request merged**
