### PR TITLE
Missed these 2 icons for gh-25

### PR DESCRIPTION
**Pull request by frapell**

### CODE REVIEW

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by frapell** [comment]
@jenkins-plone-org please run jobs

**Comment by frapell** [comment]
@mauritsvanrees @jensens Do you know what is happening with jenkins? seems to be randomly failing with unrelated issues... I forgot to include these 2 icons with my previous fix, do you think I could simply merge it as it is?

**Comment by jensens** [comment]
No idea what's up with Jenkins.  I just merged it.

**Comment by mauritsvanrees** [comment]
Jenkins was broken after I updated `Products.MailHost` to 4.11. I thought I had tested a checkout, but apparently not.
See https://github.com/plone/plone.app.discussion/issues/174 for details.
Sorry about that! Fixed now.

**Pull request merged**
