### PR TITLE
Add a direct link from a group name on Sharing tab to that group's members list

### PR DESCRIPTION
**Pull request by datakurre**
PLIP https://github.com/plone/Products.CMFPlone/issues/1310

### CODE REVIEW

**Comment by datakurre** [comment]
http://jenkins.plone.org/job/pull-request-5.0/1093/

**Comment by gforcada** [comment]
@datakurre any reason not to run it against 5.1 as well?

**Comment by datakurre** [comment]
@gforcada I forgot. Link for 5.1 job was missing from (awesome) pull request build docs.

I probably still need to add link title for this pull. Need to check, if there's one in similar controlpanel links (afk just now).

**Comment by datakurre** [comment]
http://jenkins.plone.org/job/pull-request-5.0/1096/
http://jenkins.plone.org/job/pull-request-5.1/75/

**Pull request merged**
